import "normalize.css";
import "@fontsource/poppins/400.css";
import "@fontsource/poppins/500.css";
import "@fontsource/poppins/700.css";
import "./style.css";
import "./header.css";
import "./experience.css";
import "./contacts.css";
import "./form.css";
